import Link from 'next/link';
import { supabaseClient } from '@/lib/db/client';

export const dynamic = 'force-dynamic';

export default async function ReportPage({ params }: { params: { id: string } }) {
  const id = params.id;

  const { data, error } = await supabaseClient
    .from('manual_valuations')
    .select('*')
    .eq('id', id)
    .single();

  if (error || !data) {
    return (
      <div className="w-full max-w-2xl space-y-4">
        <h1 className="text-2xl font-semibold">Valuation report</h1>
        <div className="card p-4 text-sm text-slate-300">
          Could not load this report. It may have expired or been deleted.
        </div>
        <Link href="/evaluate" className="text-brand hover:underline">
          Back to evaluator
        </Link>
      </div>
    );
  }

  const title = `${data.year} ${data.make} ${data.model}${data.trim ? ` ${data.trim}` : ''}`.trim();

  return (
    <div className="w-full max-w-2xl space-y-6">
      <div className="space-y-2">
        <div className="text-xs uppercase tracking-wide text-slate-400">Valuation report</div>
        <h1 className="text-2xl font-semibold text-white">{title}</h1>
        <p className="text-sm text-slate-300">
          Private-party estimate generated by Axle. Share this link when negotiating.
        </p>
      </div>

      <div className="card p-4 space-y-3">
        <div className="flex items-center justify-between">
          <div className="text-sm font-semibold">Fair range</div>
          <div className="text-sm text-slate-300">
            {Math.round(data.confidence * 100)}% confidence · {data.comp_count} comps
          </div>
        </div>
        <div className="text-xl font-semibold">
          ${Math.round(data.value_low / 100) / 10}k – ${Math.round(data.value_high / 100) / 10}k
        </div>
        <div className="text-sm text-slate-300">
          Mid: <span className="font-semibold text-white">${Math.round(data.value_mid / 100) / 10}k</span>
        </div>
      </div>

      <div className="card p-4">
        <div className="text-sm font-semibold">Inputs</div>
        <div className="mt-2 grid grid-cols-2 gap-3 text-xs text-slate-300">
          <div><span className="text-slate-500">Mileage:</span> {data.mileage.toLocaleString()} mi</div>
          <div><span className="text-slate-500">Condition:</span> {data.condition ?? 'n/a'}</div>
          <div><span className="text-slate-500">Transmission:</span> {data.transmission ?? 'n/a'}</div>
          <div><span className="text-slate-500">Segment:</span> {data.segment ?? 'n/a'}</div>
        </div>
      </div>

      <div className="flex gap-3">
        <Link href="/evaluate" className="btn-secondary">Run another</Link>
        <Link href="/browse" className="btn-secondary">Browse listings</Link>
      </div>

      <p className="text-xs text-slate-500">
        This report is an estimate. Always verify condition, title status, and local market dynamics.
      </p>
    </div>
  );
}
